![Clase aprendizaje no supervisado](https://raw.githubusercontent.com/MECA4605-Aprendizaje-no-supervisado/s0_repaso_conceptos/main/figs/taller-meca-aprendizaje%20no%20supervisado_banner%201169%20x%20200%20px%20-05%20-%20reduced.png)

# Revisión de Álgebra Lineal con [Numpy](http://www.numpy.org/)

Este *cuaderno* contiene una breve revisión sobre conceptos de Álgebra lineal y el uso de la librería [Numpy](http://www.numpy.org/). Dicha librería, cuyo nombre proviene de "Numerical Python", es fundamental en el ecosistema de `Python` para el procesamiento numérico y científico de datos. Una de sus principales ventajas es la inclusión de una amplia gama de funciones matemáticas para realizar operaciones de Álgebra Lineal y estadísticas, que utilizaremos en las actividades de este curso.

Al final, se encuentran ejercicios asociados a los contenidos del cuaderno para que los resuelvas por tu cuenta (no es necesario entregarlos). Si tienes dudas sobre los contenidos o los ejercicios, consulta con el tutor.

**NO** es necesario editar el archivo o hacer una entrega. Los ejemplos contienen celdas con código ejecutable (`en gris`), que podrá modificar  libremente. Esta puede ser una buena forma de aprender nuevas funcionalidades del *cuaderno*, o experimentar variaciones en los códigos de ejemplo.


## Vectores

Un vector es una serie de números que tienen un orden preestablecido, y podemos identificar cada número por un índice que indica ese orden. Podemos pensar en los vectores como las coordenadas de puntos en el espacio, con cada elemento indicando la ubicación a lo largo de un eje diferente. Existen dos tipos de vectores, los vectores fila:

$$ a = \begin{bmatrix} 5 & 9 & 7 \end{bmatrix}  $$

 y los vectores columna:

$$ b= \begin{bmatrix} 1 \\ 2 \\ 3 \end{bmatrix} $$


En `Python`, podemos representar a un *vector* con una *lista*, o preferiblemente, con un *array* de [Numpy](http://www.numpy.org/) :

- Vector como *lista* de `Python`

In [1]:
a = [5, 9, 7]
a

[5, 9, 7]

- Vectores como *array* de [Numpy](http://www.numpy.org/)

In [2]:
import numpy as np # Recordemos llamar la librería numpy

b = np.array([1, 2, 3])
b

array([1, 2, 3])

o de forma similar utilizando la función `arange`:

In [3]:
c = np.arange(1, 8)
c

array([1, 2, 3, 4, 5, 6, 7])

- Crear un vector con todos los elementos iguales a uno. Para ello podemos utilizar la función `ones` y el número de elementos:

In [4]:
d = np.ones(3)
d

array([1., 1., 1.])

 - Transformar un vector fila en un vector columna con la función de transposición, que denotamos con los símbolos $T$ o $'$. Así, el transpuesto del vector $a$ es:

    $$ a = \begin{bmatrix} 5 \\ 9 \\ 7 \end{bmatrix}  $$

    En `Python` usamos la función `transpose`:

In [5]:
np.transpose(a)

array([5, 9, 7])

### Operaciones con vectores

Para operar sobre vectores debemos  tener en cuenta ciertas particularidades de operación.

#### Suma y resta

Cuando *sumamos* dos vectores, el resultado es la suma de cada elemento del vector:


$$ \begin{split}x + y
=
\left[
\begin{array}{c}
    x_1 \\
    x_2 \\
    \vdots \\
    x_n
\end{array}
\right]
+
\left[
\begin{array}{c}
     y_1 \\
     y_2 \\
    \vdots \\
     y_n
\end{array}
\right]
=
\left[
\begin{array}{c}
    x_1 + y_1 \\
    x_2 + y_2 \\
    \vdots \\
    x_n + y_n
\end{array}
\right]\end{split}$$

En `Python`:


In [6]:
x = np.array([1, 5])
y = np.array([2, 4])

x+y


array([3, 9])

Notemos que si utilizamos dos listas obtenemos el siguiente resultado:

In [7]:
[1, 2, 3, 4] + [2, 4, 6, 8]

[1, 2, 3, 4, 2, 4, 6, 8]

En este caso `Python` no suma los elementos, sino que concatena las listas. Esta es una de las principales razones por las que preferimos utilizar arrays en [Numpy](http://www.numpy.org/) .


La resta funciona de forma análoga a la suma:

$$ \begin{split}x - y
=
\left[
\begin{array}{c}
    x_1 \\
    x_2 \\
    \vdots \\
    x_n
\end{array}
\right]
-
\left[
\begin{array}{c}
     y_1 \\
     y_2 \\
    \vdots \\
     y_n
\end{array}
\right]
=
\left[
\begin{array}{c}
    x_1 - y_1 \\
    x_2 - y_2 \\
    \vdots \\
    x_n - y_n
\end{array}
\right]\end{split}$$

En `Python`:

In [8]:
x - y

array([-1,  1])

#### Multiplicación por un escalar
La *Multiplicación por un escalar* es una operación que toma un número $\alpha$ (un escalar), y un vector $x$, para producir un nuevo vector donde cada elemento del vector $x$ es multiplicado por el número $\alpha$.

$$\begin{split}\alpha x
=
\left[
\begin{array}{c}
    \alpha x_1 \\
    \alpha x_2 \\
    \vdots \\
    \alpha x_n
\end{array}
\right]\end{split}$$

En `Python`:

In [9]:
x * 4

array([ 4, 20])

In [10]:
y * 6

array([12, 24])

#### Producto escalar

El producto escalar, también  conocido como el producto interior, de dos vectores se define como la suma de los productos de sus elementos. Solemos representarlo matemáticamente como $< x, y >$ o $x'y$, donde $x$ e $y$ son dos vectores:

$$< x, y > = x'y = \sum_{i=1}^n x_i y_i$$



En `Python` la función `dot` de [Numpy](http://www.numpy.org/) permite hacer esta operación:

In [11]:
np.dot(x, y)

np.int64(22)

de forma equivalente, podemos hacer la suma del producto:

In [12]:
sum(x * y)

np.int64(22)

Un concepto derivado del producto escalar es la *ortogonalidad*. Decimos que dos vectores son *ortogonales* cuando su producto escalar es igual a 0.

In [13]:
x = np.array([3, 4])
y = np.array([4, -3])

np.dot(x, y)

np.int64(0)

#### Norma de un vector
Relacionado al concepto de producto escalar aparece el concepto de  *norma vectorial*. La norma de un vector $x$ (que denotamos con $||x||$) es una medida de la longitud del vector.

Formalmente una norma es una función $f: \mathbb{R}^n \rightarrow \mathbb{R}$ que satisface las siguientes propiedades:

1. **No negativa.** Para todo $x\in\mathbb{R}^n,\ f(x)\geq0$.
2. **Definida.** $f(x)=0$ si y solo si $x=0$.
3. **Homogeneidad.** Para todo $x\in\mathbb{R}^n,\ c\in\mathbb{R},\ f(cx)=|c|f(x)$
4. **Desigualdad triangular.** Para todo $x, y \in\mathbb{R}^n,\ f(x+y)\leq f(x) + f(y)$

Usualmente utilizamos la norma $l_2$, también conocida como Euclideana. Esta se define como:

$$||x||_2= \sqrt{x'x} = \sqrt{\sum_{i=1}^nx_i^2}$$

Note que $||x||_2^2=x'x$.

En `Python` podemos usar la función `sqrt` y `dot`:

In [14]:
np.sqrt(np.dot(x, x))

np.float64(5.0)

o directamente usando la función `linalg.norm`:

In [15]:
np.linalg.norm(x)

np.float64(5.0)

Otro ejemplo de norma es la norma $l_1$, también conocida como la norma de Manhattan. Esta norma, frecuentemente utilizada en el análisis de datos y la optimización, se define de la siguiente manera:

$$ ||x||_1 = \sum_{i=1}^n |x_i|$$

En este caso, la norma $l_1$ mide la suma de los valores absolutos de los componentes de un vector. Esta medida es útil para evaluar la "longitud" o "magnitud" de un vector en aplicaciones prácticas, especialmente cuando se necesita un enfoque que sea más robusto frente a valores atípicos.


## Matrices

Una *matriz* es un arreglo rectangular de números (llamados entradas o elementos de la matriz) que están  ordenados en filas y columnas. Por ejemplo, la matriz $A$:

$$A=\begin{bmatrix}0 & 1& \\-1 & 2 \\ -2 & 3\end{bmatrix}$$

El número de filas y columnas nos da el orden de la matriz. Así, la matriz $A$ es de orden $3\times2$, es decir, es una matriz con 3 filas y 2 columnas.

Entonces una matriz $A$ $n \times k$ es un arreglo con n filas y k columnas, que podemos representarla de forma general de la siguiente manera:

$$\begin{split}A =
\left[
\begin{array}{cccc}
    a_{11} & a_{12} & \cdots & a_{1k} \\
    a_{21} & a_{22} & \cdots & a_{2k} \\
    \vdots & \vdots &  & \vdots \\
    a_{n1} & a_{n2} & \cdots & a_{nk}
\end{array}
\right]\end{split}$$

Donde $a_{nk}$ representa el elemento típico de la matriz ubicado en la  n-ésima  fila de la k-ésima columna.

Notemos que los vectores son casos particulares de matrices donde $n$ o $k$ son iguales a 1. En el caso de $n=1$, tenemos un *vector fila*, mientras que en el caso de $k=1$ tenemos un *vector columna*.

En `Python` creamos una matriz  utilizando una lista de vectores fila:

In [16]:
A = np.array([[1, 3, 2],
              [1, 0, 0],
              [1, 2, 2]])

B = np.array([[1, 0, 5],
              [7, 5, 0],
              [2, 1, 1]])

### Matrices especiales

#### Matriz cuadrada

Una matriz cuadrada es una matriz que tiene el mismo número de filas que de columnas. Por ejemplo, la matriz $A$ definida anteriormente.

En `Python` obtenemos  la dimensión  de una matriz, el número de filas y columnas, con la función `shape`:

In [17]:
A.shape

(3, 3)

#### Matriz identidad

La matriz identidad  es una matriz cuadrada cuyos elementos de la diagonal principal son (1) y el resto de los elementos ceros (0). Esta matriz la denotamos con la letra `I`.

Por ejemplo, la matriz identidad de 3x3 sería la siguiente:

$$I=\begin{bmatrix}1 & 0 & 0 & \\0 & 1 & 0\\ 0 & 0 & 1\end{bmatrix}$$

En `Python` utilizamos la función `eye`:

In [18]:
I = np.eye(3)
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### Matriz transpuesta

La matriz transpuesta es aquella en que las filas se transforman en columnas y las columnas en filas. Se representa con los símbolos $T$ o $'$. Por ejemplo:

$$\begin{bmatrix}a & b & \\ c & d & \\ e & f & \end{bmatrix}^T=\begin{bmatrix}a & c & e &\\b & d & f & \end{bmatrix}$$

En `Python` usamos la función `transpose`:

In [19]:
np.transpose(A)

array([[1, 1, 1],
       [3, 0, 2],
       [2, 0, 2]])

#### Matriz inversa


Denotamos con $A^{-1}$ la matriz inversa de una matriz cuadrada $A$, si se cumple que la multiplicación $A \times A^{-1}$ es igual a la matriz identidad $I$, es decir:

$$A \times A^{-1} = A^{-1} \times A = I$$

Esto implica que la matriz inversa puede no existir. En tales casos, decimos que la matriz es singular. Por lo tanto, una matriz es singular si y solo si su *determinante* es nulo.


En `Python` calculamos el determinante usando la función `linalg.det`:

In [20]:
np.linalg.det(A)

np.float64(-1.9999999999999998)

y la inversa usando `np.linalg.inv`:

In [21]:
A_inv = np.linalg.inv(A)
A_inv

array([[ 0.00000000e+00,  1.00000000e+00,  0.00000000e+00],
       [ 1.00000000e+00,  7.40148683e-17, -1.00000000e+00],
       [-1.00000000e+00, -5.00000000e-01,  1.50000000e+00]])

La matriz inversa tiene ciertas propiedades que serán útiles para algunas aplicaciones del curso:

- $(A^{-1})^{-1}=A$
- $(AB)^{-1}=B^{-1}A^{-1}$
- $(A^{-1})^T=(A^T)^{-1}$

### Operaciones con matrices

Al igual que con los *vectores*, podemos operar sobre matrices teniendo en cuenta ciertas reglas de operación.


#### Suma y resta

Cuando *sumamos* (restamos) dos matrices, el resultado es la suma (resta) de cada elemento de las matrices

$$\begin{split}A + B =
\left[
\begin{array}{ccc}
    a_{11} & \cdots & a_{1k} \\
    \vdots & \vdots & \vdots \\
    a_{n1} & \cdots & a_{nk} \\
\end{array}
\right]
+
\left[
\begin{array}{ccc}
    b_{11} & \cdots & b_{1k} \\
    \vdots & \vdots & \vdots \\
    b_{n1} & \cdots & b_{nk} \\
\end{array}
\right]
:=
\left[
\begin{array}{ccc}
    a_{11} + b_{11} &  \cdots & a_{1k} + b_{1k} \\
    \vdots & \vdots & \vdots \\
    a_{n1} + b_{n1} &  \cdots & a_{nk} + b_{nk} \\
\end{array}
\right]\end{split}$$

$$\begin{split}A - B =
\left[
\begin{array}{ccc}
    a_{11} & \cdots & a_{1k} \\
    \vdots & \vdots & \vdots \\
    a_{n1} & \cdots & a_{nk} \\
\end{array}
\right]-
\left[
\begin{array}{ccc}
    b_{11} & \cdots & b_{1k} \\
    \vdots & \vdots & \vdots \\
    b_{n1} & \cdots & b_{nk} \\
\end{array}
\right]
:=
\left[
\begin{array}{ccc}
    a_{11} - b_{11} &  \cdots & a_{1k} - b_{1k} \\
    \vdots & \vdots & \vdots \\
    a_{n1} - b_{n1} &  \cdots & a_{nk} - b_{nk} \\
\end{array}
\right]\end{split}$$

Para sumar (restar) dos matrices, debemos  tener en cuenta que solo se pueden sumar o restar matrices que tengan el mismo orden. Por ejemplo, si tenemos una matriz A de dimensión 4x3 (4 filas y 3 columnas) solo podemos sumar (restar) una matriz con las mismas dimensiones  (4x3, 4 filas y 3 columnas).

En `Python`:

- Suma

In [22]:
A + B

array([[2, 3, 7],
       [8, 5, 0],
       [3, 3, 3]])

- Resta

In [23]:
A - B

array([[ 0,  3, -3],
       [-6, -5,  0],
       [-1,  1,  1]])

#### Multiplicación por un escalar

La *Multiplicación por un escalar* es una operación que toma a un número  $\kappa$ (un escalar), y una matriz $A$, para producir una nueva matriz donde cada elemento es multiplicado por el número $\kappa$.

$$\begin{split}\kappa A
\left[
\begin{array}{ccc}
    a_{11} &  \cdots & a_{1k} \\
    \vdots & \vdots  & \vdots \\
    a_{n1} &  \cdots & a_{nk} \\
\end{array}
\right]
=
\left[
\begin{array}{ccc}
    \kappa a_{11} & \cdots & \kappa a_{1k} \\
    \vdots & \vdots & \vdots \\
    \kappa a_{n1} & \cdots & \kappa a_{nk} \\
\end{array}
\right]\end{split}$$

En `Python`:


In [24]:
A * 2

array([[2, 6, 4],
       [2, 0, 0],
       [2, 4, 4]])

In [25]:
B * 3

array([[ 3,  0, 15],
       [21, 15,  0],
       [ 6,  3,  3]])

#### Producto matricial

La multiplicación de matrices generaliza la idea del producto interior  de vectores. Para poder multiplicar matrices el número de columnas de la primera matriz debe ser igual al número de filas de la segunda matriz. El resultado de esta multiplicación va a ser una matriz que tiene el mismo número de filas que la primera matriz y el número de columnas de la segunda matriz. Por ejemplo:

$$ A_{n \times k} \times B_{k \times p} = C_{n \times p} $$

Es decir, si tenemos una matriz A de dimensión $n\times k$ y la multiplicamos por una matriz B de dimensión $k \times p$ , el resultado es una matriz C de dimensión $n \times p$.

Esto implica que la propiedad conmutativa no se cumple en el producto matricial, es decir, $AxB$ no es igual a $BxA$.

En `Python`, comenzamos definiendo una matriz A de dimensión $3 \times 4$:

In [26]:
A = np.arange(1, 13).reshape(3, 4)
A

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

y una matriz B de dimensión $4 \times 2$:

In [27]:
B = np.arange(8).reshape(4,2)
B

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

El producto resulta en una matriz de dimensión $3\times 2$:

In [28]:
A.dot(B)

array([[ 40,  50],
       [ 88, 114],
       [136, 178]])

Por otro lado, el producto de $B\times A$ arroja un error porque el numero de columnas de B no es igual al número de filas de A.

In [29]:
B.dot(A)

ValueError: shapes (4,2) and (3,4) not aligned: 2 (dim 1) != 3 (dim 0)

El elemento neutro del producto de matrices es la matriz identidad. Esto nos dice que cualquier matriz multiplicada por la matriz identidad  da como resultado la misma matriz.

In [30]:
I.dot(A)

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.],
       [ 9., 10., 11., 12.]])

#### Traza

La traza es una operación  simple que solo esta definida para matrices **cuadradas**. La traza es la suma de los elementos de la diagonal de la matriz.

$$tr(A)=\sum_ {i=1}^n A_{ii}$$

La traza tiene ciertas propiedades útiles:

- Para $A\in \mathbb{R}^{n\times n}$, $tr(A)=tr(A')$

- Para $A,B \in \mathbb{R}^{n\times n}$, $tr(A+B)=tr(A)+tr(B)$

- Para $A \in \mathbb{R}^{n\times n}$, $\gamma \in \mathbb{R}$, $tr(\gamma A)= \gamma tr(A)$

- Para $A, B$ tal que $AB$ sea una matriz cuadrada, $tr(AB)=tr(BA)$

- Para $A, B, C$ tal que $ABC$ sea una matriz cuadrada, $tr(ABC)=tr(BCA)=tr(CAB)$. Esto sin perdida de generalidad para multiplicación de más matrices.

#### Eigenvalores y eigenvectores

Un *eigenvector* (o vector propio) de $A$ es un vector no nulo $x$ que, cuando se le aplica la transformación $A$, se escala por un valor $\lambda$, llamado *eigenvalor* (o valor propio). Matemáticamente, esto se expresa como:

$$Ax=\lambda x,\ x \neq 0$$

donde

   - $A$ es una matriz $n\times n$
   - $x$ es el *eigenvalor*
   - $\lambda$ es el eigenvalor correspondiente a $x$
   
   Geométricamente, esto significa que aplicar la transformación $A$ a $x$ no cambia la dirección de $x$; solo lo escala por el factor $\lambda$. En otras palabras, los eigenvectores apuntan en direcciones que son inalteradas por la transformación, mientras que los eigenvalores indican cuánto se estiran o se comprimen esos eigenvectores.

Notemos que para cualquier eigenvector $x$ y escalar $c$, se cumple que:

$$A(cx)=cAx=c\lambda x = \lambda (cx)$$

Por lo que $cx$ también es un eigenvector. Por este motivo, y para evitar tener infinitos eigenvectores, decimos que existe "el" eigenvector asociado a $\lambda$ y que este está normalizado para tener norma 1.

#### Cómo Encontrar Eigenvalores y Eigenvectores


Para encontrar los eigenvalores de una matriz $A$, se resuelve el siguiente determinante:

$$ \text{det}(A - \lambda I) = 0 $$

Donde $I$ es la matriz identidad de la misma dimensión que $A$. Esta ecuación se llama la **ecuación característica** y es un polinomio en $\lambda$. Las soluciones a esta ecuación son los eigenvalores de $A$).

Una vez que se tienen los eigenvalores, los eigenvectores correspondientes se encuentran resolviendo el sistema de ecuaciones:

$$ (A - \lambda I) \mathbf{v} = 0 $$

Para cada eigenvalor $\lambda$.

En `Python` podemos utilizar la función `linalg.eig`:

In [31]:
A = np.array([[1, 2],
              [2, 9]])

w,v=np.linalg.eig(A)
print('Eigenvalores:', w)
print('Eigenvectores', v)

Eigenvalores: [0.52786405 9.47213595]
Eigenvectores [[-0.97324899 -0.22975292]
 [ 0.22975292 -0.97324899]]


Los eigenvalores y los eigenvectores tienen ciertas propiedades que nos serán útiles para ciertas aplicaciones en el curso. Para todos los casos vamos a suponer que $A\in\mathbb{R}^{n\times n}$ y que tiene $\lambda_i, \cdots, \lambda_n$ eigenvalores:

- La traza de $A$ es igual a la suma de los eigenvalores:
$$tr(A)=\sum_{i=1}^n\lambda_i$$

- El determinante de $A$ es igual al producto de los eigenvalores:
$$|A|=\prod_{i=1}^n\lambda_i$$

- El rango de $A$ es igual al número de eigenvalores de $A$ diferentes de cero.

- Si $A$ es no singular con eigenvalor $\lambda$ y un eigenvector asociado $x$, entonces $1/\lambda$ es un eigenvalor de $A^{-1}$ con eigenvector asociado $x$. $A^{-1}x=(1/\lambda)x$.

- Los eigenvalores de una matriz diagonal $D=diag(d_1, d_2, \cdots, d_n)$ son los elementos de la diagonal $d_1, d_2, \cdots, d_n$.

- Si la matriz $A$ tiene $n$ eigenvectores linealmente independientes, podemos ordenar esos vectores para conformar una matriz $S$ que sea cuadrada e invertible:

    $$ AS = A \begin{bmatrix} x_1 & x_2 & \cdots & x_n \end{bmatrix} $$

    $$ = \begin{bmatrix} \lambda_1 x_1 & \lambda_2 x_2 & \cdots & \lambda_n x_n \end{bmatrix} $$

    $$ S \begin{bmatrix} \lambda_1 & 0 & \cdots & 0 \\ 0 & \lambda_2 & & 0 \\ \vdots & & \ddots & \vdots \\ 0 & \cdots & 0 & \lambda_n \end{bmatrix} = S\Lambda$$
    
donde $\Lambda$ es una matriz diagonal en donde los valores que no son cero corresponden a los eigenvalores de $A$. Como las columnas de $S$ son independientes, $S^{-1}$ existe y por ende podemos multiplicar a ambos lados de $AS=S\Lambda$ por $S^{-1}$:

\begin{align}
    S^{-1}AS &=\Lambda  \\
     A &= S\Lambda S^{-1}
\end{align}    

Esta propiedad se conoce también como la descomposición espectral.


Los eigenvalores y eigenvectores son herramientas poderosas para entender las propiedades de las transformaciones lineales y tienen aplicaciones directas en técnicas de análisis de datos como el análisis de componentes principales (PCA). En PCA, los eigenvectores determinan las direcciones de máxima varianza en los datos, mientras que los eigenvalores indican la cantidad de varianza en esas direcciones. Esto permite reducir la dimensionalidad de los datos al enfocarse en las direcciones más importantes.

## Ejercicios de repaso

Resuelva los siguientes problemas. Intente realizarlos primero sin ayuda de `Python` y luego verifique su solución con los comandos de `Python`.

1. Sea $A = \begin{bmatrix} 7 & 10 \\ 1 & -2 \end{bmatrix}$, $B = \begin{bmatrix} 3 & 0 \\ 8 & -1 \end{bmatrix}$. Encuentre:

    a. $A^{9}$

    b. $B^{5}$

    c. $C=AB$
    
2. Encuentre el ángulo entre los siguientes vectores en radianes y grados.

    a. $\begin{cases}
a=2i-1j+7k\\
b=i+2j
\end{cases}$
    
    b. $\begin{cases} a = \begin{bmatrix} 1 \\ 0 \\ 1 \end{bmatrix} \\ b = \begin{bmatrix} 1 \\ 1 \\ 0 \end{bmatrix} \end{cases}$

3. Halle el área del paralelogramo limitado por las rectas $x-2y=3$, $x-2y=10$, $2x+3y=-1$ y $2x+3y=-8$ a partir del cálculo de un determinante.

4. Halle el volumen del paralelepípedo  generado por los vectores $a=[2,-1,-2]$, $b=[1,2,-3]$ y $c=[-1,3,5]$ a partir del cálculo de un determinante.

 # Conclusión

 En este *cuaderno* hicimos una breve revisión sobre vectores y matrices, y su implementación en `Python` utilizando la librería **[Numpy](http://www.numpy.org/)**. Estas van a ser algunas de las funciones que necesitaremos para el desarrollo de buena parte de las actividades de este curso.
Al ser un resumen, no es exhaustivo, por lo que lo invitamos a a explorar por si mismo y leer las documentaciones de [`Python`](https://python-docs-es.readthedocs.io/es/3.9/index.html) y [Numpy](http://www.numpy.org/).